---
- hosts: workstation

  tasks:
    - name: install various homebrew packages
      homebrew: name={{ item }} state=present
      with_items:
        - docker
        - docker-machine
      sudo: false

    - name: install terraform
      homebrew_cask: 
        name: terraform
        state: present
