---
- hosts: workstation

  tasks:
    - name: install various homebrew packages
      homebrew: name={{ item }} state=present
      with_items:
        - autojump
        - docker
        - docker-machine
      sudo: false

    - name: install terraform
      homebrew_cask: name={{ item }} state=present
      with_items:
        - terraform
      sudo: false
